path_to_data_train: /home/jupyter/datasphere/project/dino_cosface/csv_files/data_day_exp2_train.csv
path_to_data_val: /home/jupyter/datasphere/project/dino_cosface/csv_files/data_day_exp2_val.csv
path_to_checkpoint: /home/jupyter/datasphere/project/dino_cosface/checkpoints/dinov2_cosface_exp2.pth

num_classes: 3
feature_dim: 768
s: 30.0
m: 0.8